### ISSUE TITLE
実装する機能を考える

### ISSUE THREAD

**Issue by kathmandu777** [GoRuGoo/Travel_Report#1]

**Comment by kathmandu777** [comment]
このissueのコメントに書くだけでOK （PRはいらない）

**Comment by GoRuGoo** [comment]
# 概要
- 時間がないので最低限に絞るつもり
- ユーザー認証機能は絶対につけたい
- 写真投稿は実装に時間がかかりそうなので省く
- テキスト投稿形式にする  

最低限このくらいは考えましたが、学んでほしい機能があれば返信ください

**Comment by kathmandu777** [comment]
OKです。 モデル設計に移りましょう！
@GoRuGoo
